// @rebirth/defs: surviv.io v0.8.82 game definitions (generated by tools/port-survev/port.ts) with typed access, plus
// the rebirth layer (rebirth/: user-requested deviations and rebirth-only defs, applied in data.ts).
import { gameObjectsData, mapObjectsData, mapsData } from "./data.ts";
import gameConfigJson from "./generated/gameConfig.json" with { type: "json" };
import { gunBetaGuns, gunBetaLootTables } from "./rebirth/gunBeta.ts";
import { applyRebirthGameConfig } from "./rebirth/index.ts";
import { applyNewAmmoConfig } from "./rebirth/newGuns.ts";
import type {
    GameConfigDef,
    GameObjectDef,
    GameObjectDefOfType,
    GameObjectType,
    LootTableEntry,
    MapDef,
    MapObjectDef,
    MapObjectDefOfType,
    MapObjectType,
} from "./types/index.ts";

export * from "./constants.ts";
export {
    mapDefForPlayers,
    rebirthDeviations,
    rebirthOnlyIds,
    rebirthOnlyMapObjectIds,
    survevWikiSpecs,
    unscaledMapDef,
} from "./data.ts";
export * from "./gunClasses.ts";
export * from "./rebirth/darkness.ts";
export * from "./rebirth/index.ts";
export * from "./rebirth/weather.ts";
export * from "./refs.ts";
export * from "./registry.ts";
export * from "./survev/wikiSpecs.ts";
export type * from "./types/index.ts";

/** generated game objects with the rebirth deviations, then the rebirth-only defs (registry order) */
export const GameObjectDefs: Readonly<Record<string, GameObjectDef>> = gameObjectsData;
export const MapObjectDefs: Readonly<Record<string, MapObjectDef>> = mapObjectsData;
/** generated map defs with the rebirth loot tables (air drop tiers) added */
export const MapDefs: Readonly<Record<string, MapDef>> = mapsData;
/**
 * gameConfig.json (passed without a cast: tsc checks it against GameConfigDef) with the rebirth's new ammo rows (bag
 * sizes after .45 ACP, tracer colours; rebirth/newGuns.ts), then the rebirth bag items (the variant strobes) after
 * every other one
 */
export const GameConfig: GameConfigDef = applyRebirthGameConfig(applyNewAmmoConfig(gameConfigJson));

export function hasDef(id: string): boolean {
    return Object.hasOwn(GameObjectDefs, id);
}

/** Game object def by id; throws for unknown ids. */
export function getDef(id: string): GameObjectDef {
    const def = Object.hasOwn(GameObjectDefs, id) ? GameObjectDefs[id] : undefined;
    if (!def) throw new Error(`unknown game object "${id}"`);
    return def;
}

/** Game object def by id, checked to be of `type` (e.g. `getDefOfType("gun", "ak47")`); throws otherwise. */
export function getDefOfType<T extends GameObjectType>(type: T, id: string): GameObjectDefOfType<T> {
    const def = getDef(id);
    if (def.type !== type) throw new Error(`game object "${id}" is a ${def.type}, expected ${type}`);
    return def as GameObjectDefOfType<T>;
}

/** Ids of every game object of `type`, in definition order. */
export function idsOfType(type: GameObjectType): string[] {
    return Object.keys(GameObjectDefs).filter((id) => GameObjectDefs[id].type === type);
}

export function hasMapObjectDef(id: string): boolean {
    return Object.hasOwn(MapObjectDefs, id);
}

/** Map object def by id; throws for unknown ids. */
export function getMapObjectDef(id: string): MapObjectDef {
    const def = Object.hasOwn(MapObjectDefs, id) ? MapObjectDefs[id] : undefined;
    if (!def) throw new Error(`unknown map object "${id}"`);
    return def;
}

/** Map object def by id, checked to be of `type`; throws otherwise. */
export function getMapObjectDefOfType<T extends MapObjectType>(type: T, id: string): MapObjectDefOfType<T> {
    const def = getMapObjectDef(id);
    if (def.type !== type) throw new Error(`map object "${id}" is a ${def.type}, expected ${type}`);
    return def as MapObjectDefOfType<T>;
}

/** Map def by name (main, desert, woods, faction, ...); throws for unknown names. */
export function getMapDef(name: string): MapDef {
    const def = Object.hasOwn(MapDefs, name) ? MapDefs[name] : undefined;
    if (!def) throw new Error(`unknown map "${name}"`);
    return def;
}

/** Ammo of a gun id; undefined for anything that is not a gun. */
export function gunAmmo(id: string): string | undefined {
    const def = Object.hasOwn(GameObjectDefs, id) ? GameObjectDefs[id] : undefined;
    return def?.type === "gun" ? def.ammo : undefined;
}

interface GunBetaMap {
    tables: Readonly<Record<string, readonly LootTableEntry[]>>;
    guns: readonly string[];
}
const betaMaps = new Map<string, GunBetaMap>();

function gunBetaMap(mapName: string): GunBetaMap {
    let beta = betaMaps.get(mapName);
    if (!beta) {
        const tables = getMapDef(mapName).lootTable;
        beta = { tables: gunBetaLootTables(mapName, tables, gunAmmo), guns: gunBetaGuns(mapName, tables, gunAmmo) };
        betaMaps.set(mapName, beta);
    }
    return beta;
}

/**
 * A map's loot tables with the new-gun beta's floor rows (server GUN_BETA, SimRules.gunBeta; rebirth/gunBeta.ts),
 * built once per map; throws for unknown names.
 */
export function getGunBetaLootTables(mapName: string): Readonly<Record<string, readonly LootTableEntry[]>> {
    return gunBetaMap(mapName).tables;
}

/** The new-gun beta's guns a map allows, each laid GUN_BETA_FLOOR_COPIES times on its floor (rebirth/gunBeta.ts). */
export function getGunBetaGuns(mapName: string): readonly string[] {
    return gunBetaMap(mapName).guns;
}
