// Gun tier rebuild, step 4: writes docs/design/gun-tiers.md (from gun-tiers.template.md, reasons.ts and the generated
// tables), docs/design/gun-tiers-stats.md and .csv, and the ROWS for gunTiers.ts (research-cache/gun-tiers/rows.ts.txt).
// usage (repo root, after compute, score and sens): node tools/research/gun-tiers/report.ts [--apply: write the ROWS]
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { ammoTable } from "./ammo.ts";
import { REASON, ROW_COMMENTS } from "./reasons.ts";

type Any = any;
const HERE = new URL(".", import.meta.url).pathname;
const DIR = resolve("research-cache/gun-tiers");
/** the bots' tier table: its ROWS layout and comments frame the generated ROWS (--apply writes them back) */
const GUN_TIERS = resolve("packages/bots/src/knowledge/gunTiers.ts");
const inf = (_: string, v: unknown) => (v === "Infinity" ? Number.POSITIVE_INFINITY : v);
const M: Any = JSON.parse(readFileSync(`${DIR}/metrics.json`, "utf8"), inf);
const T: Any = JSON.parse(readFileSync(`${DIR}/tiers.json`, "utf8"), inf);
const row = new Map<string, Any>(M.rows.map((r: Any) => [r.id, r]));
const tier = new Map<string, Any>(T.rows.map((r: Any) => [r.id, r]));
const ORDER = ["S", "S-aim", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D"];
const CLASS_ORDER = ["lmg", "sniper", "dmr", "rifle", "shotgun", "smg", "pistol", "launcher"];
const rk = (t: string) => ORDER.indexOf(t);

const f = (x: number, d = 2) => (Number.isFinite(x) ? x.toFixed(d) : "∞");
const f0 = (x: number) => (Number.isFinite(x) ? Math.round(x).toString() : "∞");
/** display name: the def name, made unique for the winter skins and the .45 Vector */
const DISPLAY: Record<string, string> = {
    awc_winter: "AWM-S (winter)",
    svd_winter: "SVD-63 (winter)",
    sv98_winter: "SV-98 (winter)",
    vector45: "Vector .45",
};
const disp = (id: string) => DISPLAY[id] ?? row.get(id).name;
const name = (id: string) => `${disp(id)} (\`${id}\`)`;
const dmgStr = (r: Any) => {
    let s = r.pellets > 1 ? `${r.damage}x${r.pellets}` : `${r.damage}`;
    if (r.explosion) s += `+${r.explosion}e${r.shrapnel ? `+${r.shrapnel}s` : ""}`;
    return s;
};
const reloadStr = (r: Any) =>
    r.reloadType === "none"
        ? "none"
        : r.reloadType === "full"
          ? `${r.reloadTime}`
          : `${r.reloadTime}/${r.reloadType.replace("per ", "")} (${f(r.fullReload, 1)})`;
const ttk3 = (t: Any) => `${f(t.a0)} / ${f(t.a1)} / ${f(t.a2)}`;
const sortRows = (ids: string[]) =>
    ids.sort((a, b) => rk(tier.get(a).tier) - rk(tier.get(b).tier) || tier.get(b).C - tier.get(a).C);

// ---------------------------------------------------------------------------------------------------------------
// stat tables

function statTables(): string {
    const out: string[] = [];
    out.push("# Gun tier stats (generated)");
    out.push("");
    out.push(
        "Generated by `tools/research/gun-tiers/report.ts` from `compute.ts` (method: [gun-tiers.md](gun-tiers.md)). Final defs: " +
            '`@rebirth/defs` `getDefOfType("gun", id)` with the rebirth layer applied. CSV twin: ' +
            "[gun-tiers-stats.csv](gun-tiers-stats.csv).",
    );
    out.push("");
    out.push("Columns:");
    out.push("");
    out.push("- **dmg**: bullet damage x pellets, + explosion (e) + shrapnel pieces x damage (s).");
    out.push("- **RPM**: average rate (bursts and pumps included). **mag**: magazine (extended).");
    out.push("- **reload**: seconds (full magazine), or seconds per shell batch (full reload).");
    out.push(
        "- **burst / sust. DPS**: damage per second at the cyclic rate / including the reload (a charge gun: per pickup).",
    );
    out.push("- **spread**: standing / moving (degrees). **speed**: bullet or projectile u/s.");
    out.push(
        "- **TTK avg**: expected seconds from the first shot at average aim (3.5°), mean over the class band, armour none / 1 / 2.",
    );
    out.push("- **exp A1**: expert aim (1.6°) at level 1. **perf A1**: every bullet hits (15 % headshots).");
    out.push(
        "- **F**: forgiveness, expert / beginner band TTK at level 1, fixed aim error. **mob**: speed held / firing (u/s).",
    );
    out.push("- **tier**: current → proposed (`=` unchanged).");
    for (const cls of CLASS_ORDER) {
        const ids = sortRows(M.rows.filter((r: Any) => r.cls === cls).map((r: Any) => r.id));
        if (!ids.length) continue;
        const band = row.get(ids[0]).band;
        out.push("");
        out.push(`## ${cls} (band ${band[0]}-${band[band.length - 1]} u)`);
        out.push("");
        out.push(
            "| gun | dmg | RPM | mag | reload | burst DPS | sust. DPS | spread | speed | TTK avg A0 / A1 / A2 | exp A1 | perf A1 | F | mob | tier |",
        );
        out.push("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|");
        for (const id of ids) {
            const r = row.get(id);
            const t = tier.get(id);
            const cur = t.current ?? "-";
            out.push(
                `| ${disp(id)} \`${id}\` | ${dmgStr(r)} | ${f0(r.rpm)} | ${r.mag}${r.magExt !== r.mag ? ` (${r.magExt})` : ""} | ${reloadStr(r)} | ${f0(r.burstDps)} | ${f0(r.sustainedDps)} | ${r.shotSpread} / ${r.moveSpread} | ${f0(r.bulletSpeed)} | ${ttk3(r.bandTtk.average)} | ${f(r.bandTtk.expert.a1)} | ${f(r.perfect.a1)} | ${f(r.F)} | ${f(r.heldSpeed, 1)} / ${f(r.firingSpeed, 2)} | ${cur === t.tier ? `${t.tier} =` : `${cur} → ${t.tier}`} |`,
            );
        }
    }
    out.push("");
    out.push("## Other stats");
    out.push("");
    out.push(
        "| gun | class | hs x | obstacle x | burst / pump | switch | deploy group | range | falloff | ammo (spawn) | speed equip / attack / carry | special |",
    );
    out.push("|---|---|---|---|---|---|---|---|---|---|---|---|");
    for (const cls of CLASS_ORDER) {
        for (const id of sortRows(M.rows.filter((r: Any) => r.cls === cls).map((r: Any) => r.id))) {
            const r = row.get(id);
            out.push(
                `| \`${id}\`${r.dualOf ? ` (dual ${r.dualOf})` : ""} | ${r.gclass} | ${r.headshotMult} | ${r.obstacleDamage} | ${r.burst || "-"} | ${r.switchDelay} | ${r.deployGroup ?? "-"} | ${f0(r.range)} | ${r.falloff} | ${r.ammo} (${r.ammoSpawn}) | ${r.speedEquip} / ${r.speedAttack} / ${r.speedCarry} | ${r.special.join("; ") || "-"} |`,
            );
        }
    }
    out.push("");
    return out.join("\n");
}

function csv(): string {
    const cols = [
        "id",
        "name",
        "gclass",
        "cls",
        "dualOf",
        "ammo",
        "ammoFactor",
        "ammoSpawn",
        "fireMode",
        "damage",
        "pellets",
        "explosion",
        "shrapnel",
        "headshotMult",
        "obstacleDamage",
        "fireDelay",
        "burst",
        "rpm",
        "mag",
        "magExt",
        "reloadTime",
        "reloadType",
        "fullReload",
        "switchDelay",
        "deployGroup",
        "shotSpread",
        "moveSpread",
        "fsa",
        "bulletSpeed",
        "range",
        "falloff",
        "speedEquip",
        "speedAttack",
        "speedCarry",
        "heldSpeed",
        "firingSpeed",
        "mobilityCost",
        "burstDps",
        "sustainedDps",
        "magDamage",
        "killsPerMag",
        "aimK",
        "F",
        "Fdel",
    ];
    const lines = [
        [
            ...cols,
            "band",
            "perfA0",
            "perfA1",
            "perfA2",
            "expA0",
            "expA1",
            "expA2",
            "avgA0",
            "avgA1",
            "avgA2",
            "begA0",
            "begA1",
            "begA2",
            "composite",
            "compositeExpert",
            "statTier",
            "tier",
            "currentTier",
            "currentF",
            "mainMap",
        ].join(","),
    ];
    const q = (v: unknown) => {
        const s =
            v === undefined || v === null
                ? ""
                : typeof v === "number"
                  ? Number.isFinite(v)
                      ? String(Math.round(v * 1000) / 1000)
                      : "inf"
                  : String(v);
        return /[",]/.test(s) ? `"${s.replaceAll('"', '""')}"` : s;
    };
    for (const r of M.rows) {
        const t = tier.get(r.id);
        const b = r.bandTtk;
        lines.push(
            [
                ...cols.map((c) => q(r[c])),
                q(`${r.band[0]}-${r.band[r.band.length - 1]}`),
                q(r.perfect.a0),
                q(r.perfect.a1),
                q(r.perfect.a2),
                q(b.expert.a0),
                q(b.expert.a1),
                q(b.expert.a2),
                q(b.average.a0),
                q(b.average.a1),
                q(b.average.a2),
                q(b.beginner.a0),
                q(b.beginner.a1),
                q(b.beginner.a2),
                q(t.C),
                q(t.CE),
                q(t.stat),
                q(t.tier),
                q(t.current),
                q(t.currentF),
                q(t.mainMap),
            ].join(","),
        );
    }
    return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------------------------------------------
// doc sections

function tierList(inRows: boolean): string {
    const lines: string[] = [];
    for (const t of ORDER) {
        const ids = T.rows.filter((r: Any) => r.inRows === inRows && r.tier === t).sort((a: Any, b: Any) => b.C - a.C);
        if (!ids.length) continue;
        lines.push(
            `| **${t}** | ${ids.map((r: Any) => `${disp(r.id)}${r.current && r.current !== r.tier ? ` <sub>${r.current}</sub>` : ""}${r.tier !== r.stat ? "\\*" : ""}`).join(", ")} |`,
        );
    }
    return [
        "| tier | guns (best composite first; <sub>old tier</sub> when it moved; \\* = ruling or consistency, not the stat tier) |",
        "|---|---|",
        ...lines,
    ].join("\n");
}

const MS: Any = JSON.parse(readFileSync(`${DIR}/metrics-still.json`, "utf8"), inf);
const TS: Any = JSON.parse(readFileSync(`${DIR}/tiers-still.json`, "utf8"), inf);
function launcherTable(): string {
    const lines = [
        "| gun | strafing target: stat tier (composite) | TTK avg A1 | stationary target: stat tier (composite) | TTK avg A1 | current | proposed |",
        "|---|---|---|---|---|---|---|",
    ];
    const ids = ["mgl", "gl06", "m202", "rpg7", "panzerfaust", "m79", "potato_cannon", "usas"];
    for (const id of ids) {
        const t = tier.get(id);
        const ts = TS.rows.find((x: Any) => x.id === id);
        const r = row.get(id);
        const rs = MS.rows.find((x: Any) => x.id === id);
        const pk = (m: Any) =>
            m.pKillCharges !== undefined ? ` (kill per pickup ${Math.round(m.pKillCharges * 100)} %)` : "";
        lines.push(
            `| ${name(id)} | ${t.stat} (${f(t.C)}) | ${f(r.bandTtk.average.a1)}${pk(r)} | ${ts.stat} (${f(ts.C)}) | ${f(rs.bandTtk.average.a1)}${pk(rs)} | ${t.current} | ${t.tier} |`,
        );
    }
    return lines.join("\n");
}

const W = T.W;
const PART_LABEL: Record<string, string> = {
    role: "role",
    range: "range",
    alpha: "damage/shot",
    sustain: "sustain",
    handling: "handling",
    ammo: "ammo",
};
function autoReason(id: string): string {
    const r = row.get(id);
    const p = T.score[id].parts;
    const items = Object.keys(W)
        .map((k) => [k, W[k] * p[k]] as [string, number])
        .sort((a, b) => Math.abs(b[1]) - Math.abs(a[1]));
    const fact = (k: string) => {
        const b = `${r.band[0]}-${r.band[r.band.length - 1]} u`;
        if (k === "role") return `TTK ${f(r.bandTtk.average.a1)} s (avg aim, level 1) at ${b}`;
        if (k === "range")
            return r.range < 60
                ? `range ${f0(r.range)} u`
                : `kill rate across 5-80 u x${f(2 ** p.range, 2)} the median`;
        if (k === "alpha") return `${dmgStr(r)} per shot`;
        if (k === "sustain")
            return `${r.mag}-round ${r.reloadType === "none" ? "pickup" : "magazine"}, ${f(r.killsPerMag, 1)} kills each`;
        if (k === "handling")
            return `${f(r.heldSpeed, 1)} / ${f(r.firingSpeed, 2)} u/s held / firing${r.switchDelay > 0.75 ? `, switch ${r.switchDelay} s` : ""}`;
        return `${r.ammo} has no box row`;
    };
    return items
        .slice(0, 2)
        .map(([k, v]) => `${PART_LABEL[k]} ${v >= 0 ? "+" : ""}${f(v)} (${fact(k)})`)
        .join("; ");
}

function changes(): string {
    const lines = ["| gun | old | new | steps | composite | reason |", "|---|---|---|---|---|---|"];
    const moved = T.rows.filter((r: Any) => r.inRows && r.current !== r.tier);
    moved.sort(
        (a: Any, b: Any) =>
            Math.abs(rk(b.tier) - rk(b.current)) - Math.abs(rk(a.tier) - rk(a.current)) || rk(a.tier) - rk(b.tier),
    );
    for (const r of moved) {
        const steps = rk(r.current) - rk(r.tier);
        const why = REASON[r.id] ?? autoReason(r.id);
        const flag = r.flags
            .filter((x: string) => !x.startsWith("ruling agrees"))
            .map((x: string) => x.split(":")[0])
            .join(", ");
        lines.push(
            `| ${name(r.id)}${r.mainMap ? "" : " (off-map)"} | ${r.current} | ${r.tier} | ${steps > 0 ? `+${steps}` : steps} | ${f(r.C)} | ${why}${flag ? ` *(${flag})*` : ""} |`,
        );
    }
    return lines.join("\n");
}

function conflicts(): string {
    const lines = ["| gun | ruling / pin | stat tier | composite | what the numbers say |", "|---|---|---|---|---|"];
    for (const r of T.rows.filter((x: Any) => x.flags.some((fl: string) => !fl.startsWith("ruling agrees")))) {
        for (const fl of r.flags) {
            if (fl.startsWith("ruling agrees")) continue;
            lines.push(`| ${name(r.id)} | ${r.tier} | ${r.stat} | ${f(r.C)} | ${REASON[`conflict:${r.id}`] ?? fl} |`);
        }
    }
    return lines.join("\n");
}

function proposedRows(): string {
    const src = readFileSync(GUN_TIERS, "utf8");
    const start = src.indexOf("const ROWS: readonly Row[] = [");
    const end = src.indexOf("];", start);
    const body = src.slice(start, end).split("\n").slice(1);
    const out: string[] = [
        "// biome-ignore format: a few guns per line keep the table readable",
        "const ROWS: readonly Row[] = [",
    ];
    let block = 0;
    let inComment = false;
    for (const line of body) {
        const trimmed = line.trim();
        if (!trimmed) continue;
        if (trimmed.startsWith("//")) {
            const mine = inComment ? ROW_COMMENTS[block - 1] : ROW_COMMENTS[block];
            if (!inComment) {
                for (const c of mine ?? []) out.push(`    // ${c}`);
                block++;
            }
            // a null entry keeps the block's own lines (the round 6 loot notes behind the mainMap flags)
            if (mine === null) out.push(`    ${trimmed}`);
            inComment = true;
            continue;
        }
        inComment = false;
        const ids = [...trimmed.matchAll(/\["([a-z0-9_]+)",/g)].map((m) => m[1]);
        const trail = trimmed.includes("//") ? trimmed.slice(trimmed.indexOf("//") + 2).trim() : "";
        const keep = trail.replace(/^(dual )?est\.;?\s*/, "").trim();
        const cells = ids.map((id) => {
            const t = tier.get(id);
            return `["${id}", "${t.tier}", ${Math.round(t.F * 100) / 100}, ${t.mainMap}]`;
        });
        out.push(`    ${cells.join(", ")},${keep ? ` // ${keep}` : ""}`);
    }
    out.push("];");
    return out.join("\n");
}

function thresholds(): string {
    const th = T.thresholds;
    const cuts = Object.entries(th).map(([t, v]) => `${t} ≥ ${f(v as number, 3)}`);
    return `${cuts.join(", ")}, D below (S-aim: an aim gun, F ≤ ${T.F_AIM}, whose blended or expert-only composite reaches the S cut).`;
}

const tpl = readFileSync(`${HERE}gun-tiers.template.md`, "utf8");
const sens = readFileSync(`${DIR}/sens.txt`, "utf8")
    .trim()
    .split("\n")
    .map((l) => `- ${l.replace(/([a-z0-9_]+) ([A-DS][a-z+-]*)->([A-DS][a-z+-]*)/g, "`$1` $2 → $3")}`)
    .join("\n");
const doc = tpl
    .replace("{{THRESHOLDS}}", thresholds())
    .replace("{{TIERLIST}}", tierList(true))
    .replace("{{LAUNCHERS}}", launcherTable())
    .replace("{{CHANGES}}", changes())
    .replace("{{CONFLICTS}}", conflicts())
    .replace("{{ROWS}}", proposedRows())
    .replace("{{SENS}}", sens)
    .replace("{{AMMO}}", ammoTable())
    .replace(
        "{{WEIGHTS}}",
        Object.entries(W)
            .map(([k, v]) => `${PART_LABEL[k]} ${v}`)
            .join(", "),
    );
const rows = proposedRows();
writeFileSync(resolve("docs/design/gun-tiers.md"), doc);
writeFileSync(resolve("docs/design/gun-tiers-stats.md"), statTables());
writeFileSync(resolve("docs/design/gun-tiers-stats.csv"), csv());
writeFileSync(`${DIR}/rows.ts.txt`, `${rows}\n`);
if (process.argv.includes("--apply")) {
    const src = readFileSync(GUN_TIERS, "utf8");
    const start = src.indexOf("// biome-ignore format: a few guns per line keep the table readable\nconst ROWS");
    const end = src.indexOf("];", start) + 2;
    writeFileSync(GUN_TIERS, src.slice(0, start) + rows + src.slice(end));
}
console.log(
    "wrote docs/design/gun-tiers.md, gun-tiers-stats.md, gun-tiers-stats.csv; doc lines:",
    doc.split("\n").length,
);
