// Every perk of the v0.8.82 defs (41 ids) with the effect the simulation gives it and where it lives (M7a). A test
// checks that this table covers every perk def, so a new perk id cannot slip in without an effect.
// Sources: docs/research/items/perks.md "Mechanics per perk" and survev PerkProperties; values in perks/perkRules.ts.

export const PERK_EFFECTS: Readonly<Record<string, string>> = {
    leadership: "adrenaline floor 100, size +25 % (perks.ts perkMinBoost / recalcScale)",
    firepower: "extended magazines; losing it clamps loaded rounds (weaponManager ammoStats, perks.ts removePerk)",
    gotw: "regenerates the tier-1 adrenaline rate (not while downed), size +25 % (effects.ts updatePerks)",
    windwalk: "enemy bullet within 5 u or enemy explosion within 5 u: +4.8 speed for 3 s (bullets.ts, explosions.ts)",
    rare_potato: "potato swaps only roll quality 1 weapons (potatoSwap.ts)",
    aoe_heal: "heals, boosts and revives reach teammates within 8 / 6 u; x0.8 use time (consumables.ts, downed.ts)",
    endless_ammo: "reloads take no ammo except ignoreEndlessAmmo guns (weaponManager isInfinite)",
    steelskin: "x0.5 damage, bullets ricochet off the body, size +40 % (damage.ts, bullets.ts, perks.ts)",
    splinter: "main bullet x0.6 plus two x0.27 side bullets, not on noSplinter guns (shotPerks.ts, gun.ts)",
    small_arms: "size -25 %, a held gun's equip speed becomes +1 (perks.ts, player.ts computeSpeed)",
    takedown: "kills give +25 HP, +25 adrenaline and a 3 s speed burst (effects.ts onKillCredited)",
    field_medic: "no slowdown while using items, +1 speed (player.ts computeSpeed)",
    tree_climbing: "walks through trees, +2 speed in water (movement.ts, player.ts computeSpeed)",
    scavenger: "destroyed obstacles drop one more tier_world roll (drops.ts dropObstacleLoot)",
    scavenger_adv: "destroyed obstacles drop one more tier_scavenger_adv roll (drops.ts dropObstacleLoot)",
    hunted: "no effect of its own; The Hunted role shows its holder on everyone's map (roleSystem.ts indicators)",
    chambered: "first and last round x1.25, darker thick tracer, not 12 gauge (shotPerks.ts)",
    martyrdom: "12 martyr_nades on death; the Grenadier and Demo roles too (effects.ts onPerkHolderDeath)",
    targeting: "bullet damage x1.25 against players holding a perk (bullets.ts)",
    bonus_45: ".45 ACP bullets +8 %, darker tracer (shotPerks.ts)",
    broken_arrow: "a strobe's air strike calls 2 more planes: 5 instead of 3, 8 for the carpet strobe (armStrobe)",
    fabricate: "fills the pack with frag grenades every 12 s (consumables.ts updateFabricate)",
    self_revive: "a downed holder revives itself; downs instead of dying in solo (downed.ts, teams.ts, combat.ts)",
    bonus_9mm: "9mm bullets +8 %, speed and range x1.25, spread x1.1 (shotPerks.ts)",
    flak_jacket: "x0.1 explosion damage, x0.9 other damage, size +20 % (damage.ts, perks.ts)",
    explosive: "bullets explode on impact with explosion_rounds (gun.ts, bullets.ts)",
    bonus_assault: "every bullet +8 %, darker tracer (shotPerks.ts)",
    inspiration: "the bugle hastes teammates within 30 u for 3 s and recharges every 8 s (effects.ts playBugle)",
    final_bugle: "on death teammates within 60 u get +8 % damage, +20 % size and a 5 s haste (effects.ts)",
    halloween_mystery: "picking it up rolls a trick or treat perk; it drops back on death (pickup.ts, drops.ts)",
    trick_nothing: "no effect (emotes on pickup) (pickup.ts)",
    trick_size: "size +25 % (perks.ts recalcScale)",
    trick_m9: "a full cursed M9 replaces the secondary gun while held (perks.ts add / removePerk)",
    trick_chatty: "a random emote every 5-15 s (effects.ts updatePerks)",
    trick_drain: "1 bleed damage every 3 s, standing or downed (effects.ts updatePerks)",
    treat_9mm: "9mm bullets +8 %, darker tracer (shotPerks.ts)",
    treat_12g: "12 gauge pellets +8 %, darker tracer (shotPerks.ts)",
    treat_556: "5.56mm bullets +8 %, darker tracer (shotPerks.ts)",
    treat_762: "7.62mm bullets +8 %, darker tracer (shotPerks.ts)",
    treat_super: "every bullet +8 %, darker tracer (shotPerks.ts)",
    turkey_shoot: "cosmetic: emotes a turkey on pickup; clients burst victims into feathers (pickup.ts)",
};
