import { v2 } from "@rebirth/core";
import { DamageType } from "@rebirth/defs";
import { it } from "vitest";
import { openSpot, steps } from "./combatHelpers.ts";
import { addAt, flatTeamGame, hit, party } from "./teamHelpers.ts";
it("debug", () => {
    const game = flatTeamGame(4);
    const at = openSpot(game, 40);
    const [a, b] = party(game, "A", 2, at, 3);
    const enemy = addAt(game, "enemy", v2.add(at, { x: 6, y: 0 }), { group: "E", autoFill: false });
    console.log("groups", a.groupId, b.groupId, enemy.groupId, a.pos, b.pos, enemy.pos);
    game.explosions.add("explosion_frag", v2.add(a.pos, { x: 1.5, y: 0 }), 0, { gameSourceType: "frag", damageType: DamageType.Player, sourceId: a.id });
    game.step();
    console.log("health", a.health, b.health, enemy.health, a.dead, a.downed);
    const C = party(game, "C", 2, v2.add(at, { x: 0, y: 60 }), 3);
    hit(game, C[1], 200, a);
    console.log("C1", C[1].downed, C[1].dead, C[1].health);
    hit(game, C[0], 200, a);
    console.log("C0", C[0].downed, C[0].dead, "C1", C[1].dead);
});
