// Gun rarity (docs/design/gun-rarity.md): every gun's bot tier next to how often it spawns, from the final loot tables
// of @rebirth/defs (rebirth layer applied) and maps generated by the sim's mapgen.
// - per roll: the chance of each gun in one floor gun roll (`tier_guns`) and in each air drop crate (tier 1, tier 2,
//   gold with its bonus roll; the 50v50 drop), nested `tier_*` tables resolved as the sim does (loot/lootTable.ts);
// - per match: the expected copies of each gun over every loot source of the generated map (obstacle loot lists,
//   loot spawners) averaged over a few seeds at the squad ("large") scale, plus the scheduled air drops;
// - special sources: every container or spawner that is not a plain floor roll, with its chance per container.
// usage (repo root): node tools/research/gun-rarity.ts [--tiers <gunTiers.ts>] [--seeds 5] [--md <out.md>]
//   [--json <out.json>] [--tiers-note <text>]   (--tiers reads the ROWS tiers of another copy of
//   packages/bots/src/knowledge/gunTiers.ts; --tiers-note replaces the doc's line on where the tiers come from)
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { koItems } from "../../apps/client/src/l10n/ko.ts";
import { type GunTier, gunClassOf, TIER_ORDER, tieredGuns } from "../../packages/bots/src/knowledge/gunTiers.ts";
import {
    GameObjectDefs,
    getMapDef,
    getMapObjectDef,
    hasMapObjectDef,
    type LootSpawnDef,
    type LootTableEntry,
    Plane,
    tieredAirdropCrates,
} from "../../packages/defs/src/index.ts";
import { generateMap } from "../../packages/sim/src/index.ts";

type Tables = Readonly<Record<string, readonly LootTableEntry[]>>;
type Counts = Map<string, number>;

const args = process.argv.slice(2);
const arg = (name: string): string | undefined => {
    const i = args.indexOf(`--${name}`);
    return i >= 0 ? args[i + 1] : undefined;
};
const SEEDS = Array.from({ length: Number(arg("seeds") ?? 5) }, (_, i) => 1001 + i);
const MD_OUT = resolve(arg("md") ?? "docs/design/gun-rarity.md");
const JSON_OUT = arg("json");
const TIERS_FILE = arg("tiers");
/** squads: the large map scale (sim mapgen/generator.ts: teamMode > 2) */
const TEAM_MODE = 4;
const MAPS = ["main", "faction"] as const;
type MapName = (typeof MAPS)[number];
/** a special source is listed for a gun from this chance per container up */
const SPECIAL_MIN_CHANCE = 0.001;
/** tables a plain floor spot or an ordinary crate rolls: not a special source */
const PLAIN_TABLES: ReadonlySet<string> = new Set(["tier_world", "tier_container"]);
/** guns with no bot tier ("useless" to the bots) that still spawn */
const USELESS_GUNS = ["flare_gun", "flare_gun_dual", "bugle", "m9_cursed"];
/** the sim's MAX_TIER_DEPTH (loot/lootTable.ts) */
const MAX_TIER_DEPTH = 16;

const isGun = (id: string): boolean => Object.hasOwn(GameObjectDefs, id) && GameObjectDefs[id].type === "gun";
const add = (m: Counts, k: string, v: number): void => {
    if (v !== 0) m.set(k, (m.get(k) ?? 0) + v);
};

// ---------------------------------------------------------------------------------------------------------------
// Loot tables: the chance of each item in one roll (sim loot/lootTable.ts pickEntry / rollTier)

const rollMemo = new Map<string, Counts>();

/** Chance of each item from one roll of `tier` (nested tiers followed; "" and unknown tiers give nothing). */
function rollDist(map: string, tables: Tables, tier: string, depth = 0): Counts {
    const key = `${map}:${tier}`;
    const cached = rollMemo.get(key);
    if (cached) return cached;
    const out: Counts = new Map();
    const table = Object.hasOwn(tables, tier) ? tables[tier] : undefined;
    if (table && depth < MAX_TIER_DEPTH) {
        let total = 0;
        for (const e of table) if (e.weight > 0) total += e.weight;
        for (const e of table) {
            if (!(e.weight > 0) || !e.name) continue;
            const p = e.weight / total;
            if (!e.name.startsWith("tier_")) add(out, e.name, p);
            else for (const [item, q] of rollDist(map, tables, e.name, depth + 1)) add(out, item, p * q);
        }
    }
    rollMemo.set(key, out);
    return out;
}

/** What one container yields: expected copies and the chance of at least one, per gun. */
interface Yield {
    expected: Counts;
    chance: Counts;
}

/** Whether any of a loot list's rolls can give a gun from a table other than the plain floor tables. */
function isSpecialList(map: string, tables: Tables, loot: readonly LootSpawnDef[]): boolean {
    for (const l of loot) {
        if (l.tier && !PLAIN_TABLES.has(l.tier) && [...rollDist(map, tables, l.tier).keys()].some(isGun)) return true;
        if (!l.tier && l.type && isGun(l.type)) return true;
    }
    return false;
}

/**
 * Yield of an obstacle's loot list (sim rollLootList: randomInt(min, max) rolls per tier entry, fixed items as is; a
 * gun is one item whatever its count), then of the obstacle it turns into when it has loot of its own.
 */
function obstacleYield(map: string, tables: Tables, type: string, depth = 0): Yield {
    const expected: Counts = new Map();
    const none: Counts = new Map();
    const def = getMapObjectDef(type);
    if (def.type !== "obstacle") return { expected, chance: new Map() };
    for (const l of def.loot) {
        if (l.tier) {
            const min = l.min ?? 1;
            const max = Math.max(min, l.max ?? min);
            const ns = Array.from({ length: max - min + 1 }, (_, i) => min + i);
            for (const [g, p] of rollDist(map, tables, l.tier)) {
                if (!isGun(g)) continue;
                add(expected, g, ((min + max) / 2) * p);
                const miss = ns.reduce((s, n) => s + (1 - p) ** n, 0) / ns.length;
                none.set(g, (none.get(g) ?? 1) * miss);
            }
        } else if (l.type && isGun(l.type)) {
            add(expected, l.type, 1);
            none.set(l.type, 0);
        }
    }
    if (def.destroyType && hasMapObjectDef(def.destroyType) && depth < 4) {
        const next = obstacleYield(map, tables, def.destroyType, depth + 1);
        for (const [g, e] of next.expected) add(expected, g, e);
        for (const [g, c] of next.chance) none.set(g, (none.get(g) ?? 1) * (1 - c));
    }
    return { expected, chance: new Map([...none].map(([g, n]) => [g, 1 - n])) };
}

/** Yield of a loot spawner (sim spawnMapLoot: one roll per tier entry; an empty roll ends the spawner). */
function spawnerYield(map: string, tables: Tables, type: string): Yield {
    const expected: Counts = new Map();
    const def = getMapObjectDef(type);
    if (def.type !== "loot_spawner") return { expected, chance: new Map() };
    let reach = 1;
    for (const l of def.loot) {
        if (l.tier) {
            const dist = rollDist(map, tables, l.tier);
            for (const [g, p] of dist) if (isGun(g)) add(expected, g, reach * p);
            reach *= [...dist.values()].reduce((s, p) => s + p, 0);
        } else if (l.type && isGun(l.type)) add(expected, l.type, reach);
    }
    // a spawner holds at most one copy of a gun in practice (one roll per entry): chance = expected copies
    return { expected, chance: new Map(expected) };
}

const yieldMemo = new Map<string, Yield & { special: boolean }>();
function containerYield(map: string, tables: Tables, type: string): Yield & { special: boolean } {
    const key = `${map}:${type}`;
    let y = yieldMemo.get(key);
    if (!y) {
        const def = getMapObjectDef(type);
        const base = def.type === "loot_spawner" ? spawnerYield(map, tables, type) : obstacleYield(map, tables, type);
        const loot = def.type === "obstacle" || def.type === "loot_spawner" ? def.loot : [];
        y = { ...base, special: isSpecialList(map, tables, loot) };
        yieldMemo.set(key, y);
    }
    return y;
}

// ---------------------------------------------------------------------------------------------------------------
// Map walk: expected number of each container per match

/**
 * Adds the containers (obstacles and loot spawners) a map object brings, `w` copies of it: a building's children with
 * its weighted child types as chances (sim mapgen/generator.ts genBuilding, map spawn replacements applied unless the
 * child ignores them), a structure's layers. `type` is already replaced.
 */
function addContainers(type: string, w: number, repl: Readonly<Record<string, string>>, out: Counts, depth = 0): void {
    if (!hasMapObjectDef(type) || depth > 12) return;
    const def = getMapObjectDef(type);
    if (def.type === "obstacle" || def.type === "loot_spawner") add(out, type, w);
    else if (def.type === "structure")
        for (const layer of def.layers) addContainers(layer.type, w, repl, out, depth + 1);
    else if (def.type === "building") {
        for (const child of def.mapObjects) {
            const options: Array<[string, number]> =
                typeof child.type === "string"
                    ? [[child.type, 1]]
                    : Object.entries(child.type).filter(([, v]) => v > 0);
            const total = options.reduce((s, [, v]) => s + v, 0);
            for (const [t, v] of options) {
                if (!t) continue;
                const real = child.ignoreMapSpawnReplacement ? t : (repl[t] ?? t);
                addContainers(real, (w * v) / total, repl, out, depth + 1);
            }
        }
    }
}

/** Expected containers per match: the top-level objects of `SEEDS` generated maps, averaged. */
function containersPerMatch(map: MapName): { counts: Counts; realized: Counts } {
    const repl = getMapDef(map).mapGen.spawnReplacements[0] ?? {};
    const counts: Counts = new Map();
    const realized: Counts = new Map();
    const w = 1 / SEEDS.length;
    for (const seed of SEEDS) {
        const gen = generateMap(map, seed, TEAM_MODE);
        for (const o of gen.objects) {
            if (o.parentId === 0) addContainers(o.type, w, repl, counts);
            if (o.kind === "obstacle") add(realized, o.type, w);
        }
        for (const s of gen.lootSpawns) {
            if (s.parentId === 0) add(counts, s.type, w);
            add(realized, s.type, w);
        }
    }
    return { counts, realized };
}

// ---------------------------------------------------------------------------------------------------------------
// Air drops (sim match/planes.ts): every scheduled drop plane, its crate picked by the map's weights, normal shells
// split into tier 1 / tier 2 by the circle (defs tieredAirdropCrates)

function airdropCratesPerMatch(map: MapName): Counts {
    const planes = getMapDef(map).gameConfig.planes;
    const out: Counts = new Map();
    for (const timing of planes.timings) {
        if (timing.options.type !== Plane.Airdrop) continue;
        const choices = tieredAirdropCrates(planes.crates, timing.circleIdx);
        const total = choices.reduce((s, c) => s + c.weight, 0);
        for (const c of choices) {
            const shell = getMapObjectDef(c.name);
            const inner = c.inner ?? (shell.type === "obstacle" ? (shell.destroyType ?? "") : "");
            if (inner) add(out, inner, c.weight / total);
        }
    }
    return out;
}

// ---------------------------------------------------------------------------------------------------------------
// Tiers (the bots' list, or the ROWS of another copy of gunTiers.ts)

function tiersFrom(file: string | undefined): Map<string, GunTier> {
    const out = new Map<string, GunTier>();
    if (!file) {
        for (const t of tieredGuns()) out.set(t.id, t.tier);
        return out;
    }
    const src = readFileSync(resolve(file), "utf8");
    const body = src.slice(src.indexOf("const ROWS"), src.indexOf("];", src.indexOf("const ROWS")));
    for (const m of body.matchAll(/\["([a-z0-9_]+)",\s*"([^"]+)",\s*[\d.]+,\s*(?:true|false)\]/g)) {
        if (!TIER_ORDER.includes(m[2] as GunTier)) throw new Error(`${file}: unknown tier ${m[2]} for ${m[1]}`);
        out.set(m[1], m[2] as GunTier);
    }
    if (out.size < 50) throw new Error(`${file}: only ${out.size} tier rows parsed`);
    return out;
}

// ---------------------------------------------------------------------------------------------------------------
// Rarity labels

const LABELS = [
    { label: "흔함", min: 3 },
    { label: "보통", min: 1 },
    { label: "희귀", min: 0.25 },
    { label: "매우 희귀", min: 0.05 },
    { label: "극악", min: Number.MIN_VALUE },
    { label: "안 나옴", min: 0 },
] as const;
const labelOf = (copies: number): string => (LABELS.find((l) => copies >= l.min) ?? LABELS[5]).label;

const CLASS_ORDER = ["lmg", "rifle", "dmr", "sniper", "shotgun", "smg", "pistol", "launcher", "useless"];
const CLASS_KO: Readonly<Record<string, string>> = {
    lmg: "경기관총",
    rifle: "돌격소총",
    dmr: "지정사수소총",
    sniper: "저격소총",
    shotgun: "산탄총",
    smg: "기관단총",
    pistol: "권총",
    launcher: "발사기",
    useless: "기타",
};
/** Plain Korean names of the containers that are special sources or air drops (docs/research/maps/obstacles.md). */
const SOURCE_NAMES: Readonly<Record<string, string>> = {
    crate_10t1: "1단계 보급",
    crate_10t2: "2단계 보급",
    crate_11: "황금 보급",
    crate_12: "50v50 대형 보급",
    case_07: "목욕탕 반지 케이스",
    deposit_box_02_club: "클럽 비밀방 총 보관함",
    deposit_box_02: "금고 보관함(은행·목욕탕)",
    mil_crate_04: "목욕탕 군용 상자",
    mil_crate_02: "OT-38 상자",
    crate_02: "소련 상자",
    crate_14a: "클럽 병 상자",
    crate_02f: "레드팀 보급 상자(50v50)",
    crate_22: "블루팀 보급 상자(50v50)",
    crate_07: "벙커 AK 상자",
    crate_09: "소라 상자",
    toilet_01: "변기",
    toilet_02: "헌 변기",
    toilet_04: "경찰서·벙커 변기",
    drawers_02: "화분 서랍장",
    bookshelf_02: "화분 책장",
    barrel_04: "맨션 지하 금색 통",
    gun_mount_01: "오두막 벽걸이 총",
    gun_mount_02: "오두막 벽걸이 총",
    gun_mount_03: "오두막 벽걸이 총",
    gun_mount_05: "오두막 벽걸이 총",
    loot_tier_sv98: "컨테이너 속 SV-98",
    case_01: "금고방 데저트이글 케이스",
    case_02: "금고방 듀얼 데저트이글 케이스",
    case_03: "벙커 손도끼 케이스",
    case_06: "국화 상자",
    locker_02: "경찰서 황금 사물함",
    locker_03: "벙커 사물함",
    chest_01: "해적 보물 상자",
    chest_02: "궤짝(작업장·벌목장)",
    chest_03f: "강 상자",
    chest_04: "헛간 지하 황금 눈 상자",
    pot_02: "황금 오두막 화분",
    pot_05: "정찰 오두막 화분",
    tree_03: "은닉 나무",
    tree_03f: "은닉 나무",
    stone_02: "은닉 바위",
    stone_02f: "은닉 바위",
    stone_08: "강 은닉 바위",
    stone_04: "하드스톤 블록",
};
const sourceName = (type: string): string => SOURCE_NAMES[type] ?? type;

// ---------------------------------------------------------------------------------------------------------------
// Compute

interface SourceRow {
    name: string;
    /** chance a container holds the gun (expected copies for spawners) */
    chance: number;
    /** containers of this kind per match */
    perMatch: number;
}
interface MapResult {
    floor: number;
    drop: Readonly<Record<string, number>>;
    perMatch: number;
    fromDrops: number;
    label: string;
    special: SourceRow[];
    /** expected copies per match by source, biggest first */
    bySource: Array<{ name: string; copies: number }>;
}
interface GunRow {
    id: string;
    name: string;
    cls: string;
    tier: GunTier | null;
    dual: boolean;
    maps: Record<MapName, MapResult>;
}

/** The air drop crates shown per drop: main's tier 1, tier 2 and gold, 50v50's big military drop. */
const DROP_CRATES: Readonly<Record<MapName, Readonly<Record<string, string>>>> = {
    main: { tier1: "crate_10t1", tier2: "crate_10t2", gold: "crate_11" },
    faction: { faction: "crate_12" },
};

const tiers = tiersFrom(TIERS_FILE);
const perMap = new Map<MapName, { counts: Counts; drops: Counts; tables: Tables }>();
for (const map of MAPS) {
    const { counts, realized } = containersPerMatch(map);
    const tables = getMapDef(map).lootTable;
    perMap.set(map, { counts, drops: airdropCratesPerMatch(map), tables });
    // the analytic walk against the realized maps (they differ only by the weighted building children)
    const off = [...counts]
        .filter(([t, n]) => Math.abs((realized.get(t) ?? 0) - n) > 0.5 + 0.25 * n)
        .map(([t, n]) => `${t} ${n.toFixed(2)}/${(realized.get(t) ?? 0).toFixed(2)}`);
    console.log(`${map}: ${counts.size} container kinds; walk vs realized differ on: ${off.join(", ") || "none"}`);
}

const reachable = new Set<string>();
for (const [map, { counts, drops, tables }] of perMap) {
    for (const t of [...counts.keys(), ...drops.keys()])
        for (const g of containerYield(map, tables, t).expected.keys()) reachable.add(g);
}
// every tiered gun, the untiered ones that spawn, and the useless ones; off-map untiered guns (dev guns) are left out
const ids = [...new Set([...tiers.keys(), ...USELESS_GUNS, ...reachable])].filter(isGun);

function mapResult(map: MapName, id: string): MapResult {
    const { counts, drops, tables } = perMap.get(map)!;
    const floor = rollDist(map, tables, "tier_guns").get(id) ?? 0;
    const drop: Record<string, number> = {};
    for (const [k, crate] of Object.entries(DROP_CRATES[map]))
        drop[k] = containerYield(map, tables, crate).chance.get(id) ?? 0;
    const bySource: Counts = new Map();
    const special = new Map<string, { chanceSum: number; perMatch: number }>();
    let perMatch = 0;
    for (const [type, n] of counts) {
        const y = containerYield(map, tables, type);
        const e = (y.expected.get(id) ?? 0) * n;
        perMatch += e;
        add(bySource, y.special ? sourceName(type) : "바닥·일반 상자", e);
        const chance = y.chance.get(id) ?? 0;
        if (y.special && chance >= SPECIAL_MIN_CHANCE) {
            const s = special.get(sourceName(type)) ?? { chanceSum: 0, perMatch: 0 };
            s.chanceSum += chance * n;
            s.perMatch += n;
            special.set(sourceName(type), s);
        }
    }
    let fromDrops = 0;
    for (const [crate, n] of drops) fromDrops += (containerYield(map, tables, crate).expected.get(id) ?? 0) * n;
    add(bySource, "보급", fromDrops);
    perMatch += fromDrops;
    return {
        floor,
        drop,
        perMatch,
        fromDrops,
        label: labelOf(perMatch),
        special: [...special]
            .map(([name, s]) => ({ name, chance: s.chanceSum / s.perMatch, perMatch: s.perMatch }))
            .sort((a, b) => b.chance - a.chance),
        bySource: [...bySource]
            .filter(([, c]) => c > 0)
            .map(([name, copies]) => ({ name, copies }))
            .sort((a, b) => b.copies - a.copies),
    };
}

const tierRankOf = (t: GunTier | null): number => (t ? TIER_ORDER.indexOf(t) : -1);
const rows: GunRow[] = ids
    .map((id) => ({
        id,
        name: koItems[id] ?? (GameObjectDefs[id] as { name?: string }).name ?? id,
        cls: gunClassOf(id) ?? "useless",
        tier: tiers.get(id) ?? null,
        dual: id.endsWith("_dual"),
        maps: { main: mapResult("main", id), faction: mapResult("faction", id) },
    }))
    .sort(
        (a, b) =>
            tierRankOf(b.tier) - tierRankOf(a.tier) ||
            CLASS_ORDER.indexOf(a.cls) - CLASS_ORDER.indexOf(b.cls) ||
            b.maps.main.perMatch - a.maps.main.perMatch ||
            a.id.localeCompare(b.id),
    );

// ---------------------------------------------------------------------------------------------------------------
// Output

/** Percent with two significant digits ("–" for zero). */
function pct(p: number): string {
    if (p <= 0) return "–";
    const v = p * 100;
    if (v > 99.95) return "100%";
    return `${Number(v >= 10 ? v.toFixed(1) : v.toPrecision(2))}%`;
}
/** Copies with two significant digits below 10. */
function num(n: number): string {
    if (n <= 0) return "0";
    return n >= 10 ? n.toFixed(1) : Number(n.toPrecision(2)).toString();
}
const specialText = (s: SourceRow[], limit = 4): string =>
    s.length === 0
        ? ""
        : s
              .slice(0, limit)
              .map((r) => `${r.name} ${pct(r.chance)}`)
              .join(", ") + (s.length > limit ? ` 외 ${s.length - limit}곳` : "");

function dropsPerMatchText(map: MapName): string {
    return [...perMap.get(map)!.drops].map(([crate, n]) => `${sourceName(crate)} ${num(n)}`).join(", ");
}

const tierCell = (t: GunTier | null): string => t ?? "—";
const table = [
    "| 총 | id | class | tier | 바닥 % | 보급 1단계 % | 보급 2단계 % | 황금 % | special sources | 판당 기대 개수 (main) | 판당 기대 개수 (50v50) | label (main / 50v50) |",
    "|---|---|---|---|--:|--:|--:|--:|---|--:|--:|---|",
    ...rows.map((r) => {
        const m = r.maps.main;
        const f = r.maps.faction;
        const special = [specialText(m.special), r.dual && m.floor === 0 ? "싱글 2정 조합" : ""]
            .filter(Boolean)
            .join("; ");
        const label = m.label === f.label ? m.label : `${m.label} / ${f.label}`;
        return `| ${r.name} | \`${r.id}\` | ${CLASS_KO[r.cls] ?? r.cls} | ${tierCell(r.tier)} | ${pct(m.floor)} | ${pct(m.drop.tier1)} | ${pct(m.drop.tier2)} | ${pct(m.drop.gold)} | ${special} | ${num(m.perMatch)} | ${num(f.perMatch)} | ${label} |`;
    }),
];
const factionDrop = rows
    .filter((r) => r.maps.faction.drop.faction > 0)
    .sort((a, b) => b.maps.faction.drop.faction - a.maps.faction.drop.faction)
    .map((r) => `${r.name} ${pct(r.maps.faction.drop.faction)}`)
    .join(", ");

const tiersNote =
    arg("tiers-note") ??
    (TIERS_FILE
        ? `the tier column is read from the \`ROWS\` of \`${TIERS_FILE}\``
        : "the tier column is `tieredGuns()` of `packages/bots/src/knowledge/gunTiers.ts`");
const md = `# Gun tiers and rarity

Generated by \`node tools/research/gun-rarity.ts\` (repository root); ${tiersNote}. Do not edit the table by hand.

## Method

- **Loot.** The final loot tables of \`@rebirth/defs\` \`getMapDef(name).lootTable\` (rebirth layer applied: air drop
  tiers, the owner's 2026-10-08 weights, the new guns as normal loot; \`GUN_BETA\`'s extra floor copies left out).
  Nested \`tier_*\` rows are resolved as the sim rolls them (\`packages/sim/src/loot/lootTable.ts\`): one weighted pick
  per level, \`""\` gives nothing, a gun is one item whatever its count.
- **바닥 %.** The chance of the gun in one floor gun roll (\`tier_guns\`) of the classic map (\`main\`).
- **보급 %.** The chance that one air drop holds the gun: tier 1 (\`crate_10t1\`, with its 10 % tier 2 re-roll), tier 2
  (\`crate_10t2\`) and gold (\`crate_11\`: the \`tier_airdrop_rare\` main gun or the \`tier_airdrop_gold_bonus\` roll).
- **Special sources.** Every container or loot spawner of the map that can give the gun from a table other than the
  plain floor rolls (\`tier_world\`, \`tier_container\`) or as a fixed item, with the chance one such container holds
  it (listed from ${pct(SPECIAL_MIN_CHANCE)}; at most four, best first). Boxes that roll the floor gun table
  itself (Soviet crates, toilets, bank deposit boxes, 50v50 team crates) are listed too: floor odds, more rolls.
- **판당 기대 개수.** Maps from the sim's \`generateMap(map, seed, 4)\` (squad, "large" scale), seeds
  ${SEEDS.join(", ")}, averaged. Every top-level object is walked through its building and structure defs
  (weighted child types as chances, the map's spawn replacements), and the expected copies of every obstacle loot
  list and loot spawner are summed, as if every container on the map were opened. Players' starting gear, dead players' drops, the
  Scavenger perks' extra rolls and 50v50 role loadouts are not loot and are not counted.
- **Air drops per match.** Every scheduled drop plane of the map's \`gameConfig.planes\` (type 0), its crate picked by
  the crate weights with the circle's tier 1 share (\`tieredAirdropCrates\`). Per match: main
  ${dropsPerMatchText("main")}; 50v50 ${dropsPerMatchText("faction")}. This assumes the match reaches every drop
  circle (main 1 and 3, 50v50 2 and 4) and counts no drop called by a flare gun.
- **Label** (from 판당 기대 개수): 흔함 ≥ 3, 보통 1–3, 희귀 0.25–1, 매우 희귀 0.05–0.25, 극악 < 0.05, 안 나옴 0.
  Dual pistols that never spawn as a pair come from picking up two singles ("싱글 2정 조합").

**Coming map change.** The classic and 50v50 maps are about to grow by 20 % per side, with building counts scaled by
area. The per-match counts will then grow a little; the per-roll chances (바닥, 보급, special sources) will not change.

## Table

Sorted by tier (best first), then class, then 판당 기대 개수 on main.

${table.join("\n")}

## 50v50 air drop

50v50 has no tiered or gold drop: its drop (\`airdrop_crate_03\` → \`crate_12\`, 2 per match) rolls
\`tier_airdrop_rare\` twice and \`tier_airdrop_uncommon\` 7-8 times. Chance per drop: ${factionDrop}.
`;
writeFileSync(MD_OUT, md);
console.log(`wrote ${MD_OUT} (${rows.length} guns)`);

if (JSON_OUT) {
    const data = {
        seeds: SEEDS,
        tiersFrom: tiersNote,
        dropsPerMatch: Object.fromEntries(MAPS.map((m) => [m, dropsPerMatchText(m)])),
        rows: rows.map((r) => ({
            ...r,
            maps: Object.fromEntries(
                MAPS.map((m) => [
                    m,
                    {
                        ...r.maps[m],
                        special: r.maps[m].special.slice(0, 6),
                        bySource: r.maps[m].bySource.slice(0, 5),
                    },
                ]),
            ),
        })),
    };
    const round = (_: string, v: unknown) =>
        typeof v === "number" && !Number.isInteger(v) ? Number(v.toPrecision(4)) : v;
    writeFileSync(resolve(JSON_OUT), JSON.stringify(data, round));
    console.log(`wrote ${JSON_OUT}`);
}
