// Compares the original client definitions (Kongregate relaunch = v0.8.82 + 2026 fixes) with survev's defs.
// Usage: node --experimental-transform-types tools/research/live-vs-survev.ts
// Inputs: research-cache/live/defs.json (tools/research/extract-live-defs.ts), .survev
// Outputs: docs/research/data/live-vs-survev.json, docs/research/provenance/live-vs-survev.md
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SURVEV = resolve(".survev");
const live = JSON.parse(readFileSync("research-cache/live/defs.json", "utf8"));
const { RawGameObjectDefs } = await import(`${SURVEV}/shared/defs/gameObjectDefs.ts`);
const { RawMapObjectDefs: survevMapObjects } = await import(`${SURVEV}/shared/defs/mapObjectDefs.ts`);

const COSMETIC =
    /img|image|sprite|tint|sound|lore|rarity|particle|anim|scale|sfx|alpha|zIdx|color|map\.|icon|mirror|pose|worldImg|lootImg|handImg|hipImg|ceilingImg|floorImg|explodeParticle|hitParticle|decal|emitter|trail|border|caseTiming|shell|desc\.|name$/i;

function flatten(obj: unknown, prefix = "", out: Record<string, string> = {}): Record<string, string> {
    if (Array.isArray(obj)) {
        if (obj.every((x) => x === null || typeof x !== "object")) out[prefix] = JSON.stringify(obj);
        else
            obj.forEach((x, i) => {
                flatten(x, `${prefix}[${i}]`, out);
            });
    } else if (obj && typeof obj === "object") {
        for (const [k, v] of Object.entries(obj)) flatten(v, prefix ? `${prefix}.${k}` : k, out);
    } else if (obj !== undefined)
        out[prefix] = typeof obj === "number" ? String(Math.round(obj * 1e6) / 1e6) : JSON.stringify(obj);
    return out;
}

interface FieldDiff {
    field: string;
    live: string | undefined;
    survev: string | undefined;
}
interface Entry {
    id: string;
    type: string;
    status: "both" | "survev-only" | "live-only";
    diffs: FieldDiff[];
}

function compare(liveDefs: Record<string, any>, survevDefs: Record<string, any>): Entry[] {
    const ids = new Set([...Object.keys(liveDefs), ...Object.keys(survevDefs)]);
    const out: Entry[] = [];
    for (const id of [...ids].sort()) {
        const l = liveDefs[id];
        const s = survevDefs[id];
        const type = (l ?? s)?.type ?? "?";
        if (!l || !s) {
            out.push({ id, type, status: l ? "live-only" : "survev-only", diffs: [] });
            continue;
        }
        const fl = flatten(l);
        const fs = flatten(s);
        const diffs: FieldDiff[] = [];
        for (const f of new Set([...Object.keys(fl), ...Object.keys(fs)])) {
            if (fl[f] === fs[f]) continue;
            // treat absent and falsy defaults as equal
            const falsy = (v: string | undefined) =>
                v === undefined || v === "false" || v === "0" || v === '""' || v === "null";
            if (falsy(fl[f]) && falsy(fs[f])) continue;
            diffs.push({ field: f, live: fl[f], survev: fs[f] });
        }
        out.push({ id, type, status: "both", diffs });
    }
    return out;
}

const go = compare(live.gameObjects, RawGameObjectDefs);
const mo = compare(live.mapObjects, survevMapObjects);
writeFileSync("docs/research/data/live-vs-survev.json", JSON.stringify({ gameObjects: go, mapObjects: mo }, null, 1));

const summarize = (entries: Entry[]) => {
    const byType: Record<string, { both: number; survevOnly: number; liveOnly: number; changed: number }> = {};
    for (const e of entries) {
        const t = (byType[e.type] ??= { both: 0, survevOnly: 0, liveOnly: 0, changed: 0 });
        if (e.status === "both") t.both++;
        else if (e.status === "survev-only") t.survevOnly++;
        else t.liveOnly++;
        if (e.diffs.some((d) => !COSMETIC.test(d.field))) t.changed++;
    }
    return byType;
};

const esc = (v: string | undefined) =>
    (v === undefined ? "—" : v.length > 60 ? `${v.slice(0, 57)}...` : v).replace(/\|/g, "\\|");
const LIVE = "[src:kong/relaunch-client-defs]";
const md: string[] = [
    "# Original client (v0.8.82) vs survev defs",
    "",
    "> Generated by `node --experimental-transform-types tools/research/live-vs-survev.ts`. Do not edit by hand.",
    "> The original definitions come from the client bundle served by the 2026 Kongregate relaunch (surviv.io), whose changelog is v0.8.82 plus 0.9.0–0.9.3 fixes (2026). Extracted with `tools/research/extract-live-defs.ts`.",
    "> Only client-side definitions exist in that bundle: game objects and map objects. Server-only data (loot tables, map generation, gas) is not in it.",
    "",
];
for (const [label, entries, file] of [
    ["Game objects", go, "shared/defs/gameObjectDefs.ts"],
    ["Map objects", mo, "shared/defs/mapObjectDefs.ts"],
] as const) {
    md.push(
        `## ${label}: coverage`,
        "",
        "| type | in both | survev only | original only | changed gameplay fields |",
        "|---|---|---|---|---|",
    );
    for (const [t, s] of Object.entries(summarize(entries)).sort()) {
        md.push(
            `| ${t} | ${s.both} | ${s.survevOnly} | ${s.liveOnly} | ${s.changed} [src:derived/live-vs-survev] [H] |`,
        );
    }
    md.push("", `## ${label}: only in survev (fork or post-0.8.82)`, "");
    const survevOnly = entries.filter((e) => e.status === "survev-only");
    for (const t of [...new Set(survevOnly.map((e) => e.type))].sort()) {
        md.push(
            `- ${t}: ${survevOnly
                .filter((e) => e.type === t)
                .map((e) => e.id)
                .join(", ")} [src:survev/${file}] ${LIVE} [H]`,
        );
    }
    const liveOnly = entries.filter((e) => e.status === "live-only");
    md.push("", `## ${label}: only in the original client`, "");
    if (!liveOnly.length) md.push(`- none [src:derived/live-vs-survev] [H]`);
    for (const t of [...new Set(liveOnly.map((e) => e.type))].sort()) {
        md.push(
            `- ${t}: ${liveOnly
                .filter((e) => e.type === t)
                .map((e) => e.id)
                .join(", ")} ${LIVE} [H]`,
        );
    }
    md.push(
        "",
        `## ${label}: gameplay field differences`,
        "",
        "| id | field | original | survev | sources |",
        "|---|---|---|---|---|",
    );
    for (const e of entries) {
        for (const d of e.diffs.filter((d) => !COSMETIC.test(d.field))) {
            md.push(`| ${e.id} | ${d.field} | ${esc(d.live)} | ${esc(d.survev)} | ${LIVE} [src:survev/${file}] [H] |`);
        }
    }
    md.push("");
}
md.push(
    "## Conflicts",
    "",
    "- every row in the difference tables is a survev change against the original client; the original value wins for the v0.8.82 target [src:derived/live-vs-survev] [H]",
    "",
    "## Open questions",
    "",
    "- whether any 0.9.x (2026) relaunch fix changed a definition value [src:kong/relaunch-changelog] [L]",
    "",
);
writeFileSync("docs/research/provenance/live-vs-survev.md", md.join("\n"));

for (const [label, entries] of [
    ["gameObjects", go],
    ["mapObjects", mo],
] as const) {
    const s = summarize(entries);
    const tot = Object.values(s).reduce((a, b) => ({
        both: a.both + b.both,
        survevOnly: a.survevOnly + b.survevOnly,
        liveOnly: a.liveOnly + b.liveOnly,
        changed: a.changed + b.changed,
    }));
    console.log(label, JSON.stringify(tot));
}
