// Coverage of the map object definition fields by the simulation: every field present in the obstacle, building and
// structure defs (nested door, button, ceiling, floor, puzzle, child, heal region, stair, layer and interior sound
// fields included) is listed with what handles it. test/fieldCoverage.test.ts fails when the defs gain a field that
// is not triaged here, or when this table lists a field the defs no longer have.
// Status meanings: "implemented" (the simulation applies it; `where` names the code), "client" (presentation only:
// the client reads it from the defs), "mapgen" (map generation), "data" (definition metadata or factory parameters
// with no behaviour of their own), "unused" (no logic in survev's server or client either), "deferred" (gameplay
// still to do in `milestone`).

export type FieldStatus =
    | { status: "implemented"; where: string }
    | { status: "client" | "mapgen" | "data" | "unused"; note?: string }
    | { status: "deferred"; milestone: string; note: string };

const impl = (where: string): FieldStatus => ({ status: "implemented", where });
const client = (note?: string): FieldStatus => ({ status: "client", note });
const mapgen = (note?: string): FieldStatus => ({ status: "mapgen", note });
const data = (note?: string): FieldStatus => ({ status: "data", note });
const unused = (note: string): FieldStatus => ({ status: "unused", note });
const deferred = (milestone: string, note: string): FieldStatus => ({ status: "deferred", milestone, note });

const factoryParam = data("parameter of the original building factory, kept in the data");

/** Field path ("obstacle.door.autoOpen", "building.ceiling.destroy.wallCount", ...) -> how it is handled. */
export const BEHAVIOUR_FIELDS: Readonly<Record<string, FieldStatus>> = {
    // obstacles
    "obstacle.type": data(),
    "obstacle.obstacleType": deferred("M8", "destruction quests count obstacle categories"),
    "obstacle.scale": impl("mapgen spawn scale; entities.ts Obstacle shrinks to scale.destroy with its health"),
    "obstacle.collision": impl("entities.ts Obstacle.collider"),
    "obstacle.height": impl("bullets.ts, melee.ts, explosions.ts, projectiles.ts height tests"),
    "obstacle.collidable": impl("player.ts moveWithCollision, loot.ts, bullets.ts"),
    "obstacle.destructible": impl("entities.ts Obstacle.damage"),
    "obstacle.explosion": impl("combat.ts onObstacleDestroyed"),
    "obstacle.health": impl("entities.ts Obstacle.damage"),
    "obstacle.hitParticle": client(),
    "obstacle.explodeParticle": client(),
    "obstacle.reflectBullets": impl("bullets.ts reflect"),
    "obstacle.loot": impl("drops.ts dropObstacleLoot"),
    "obstacle.map": client("minimap"),
    "obstacle.terrain": mapgen(),
    "obstacle.img": client(),
    "obstacle.sound": client(),
    "obstacle.isBush": client("leaf particles and sound when walking through"),
    "obstacle.mapObstacleBounds": mapgen(),
    "obstacle.button": impl("interact.ts useButton"),
    "obstacle.armorPlated": impl("combat.ts canDamageObstacle (needs an armorPiercing source)"),
    "obstacle.isDecalAnchor": impl("buildings.ts removeAnchoredDecals"),
    "obstacle.dropCollision": client("air drop shadow; survev's server does not read it"),
    "obstacle.airdropCrate": deferred("M8", "the airdrop_unlocked quest event"),
    "obstacle.destroyType": impl("drops.ts spawnDestroyType"),
    "obstacle.smartLoot": impl("drops.ts destroyTypeOf / lootOwnerOf (class roles: roles/roles.ts, M7a)"),
    "obstacle.lootSpawn": impl("drops.ts dropObstacleLoot"),
    "obstacle.createSmoke": impl("combat.ts onObstacleDestroyed"),
    "obstacle.swapWeaponOnDestroy": impl("potatoSwap.ts randomWeaponSwap"),
    "obstacle.regrow": impl("combat.ts onObstacleDestroyed, interact.ts updateObstacleTimers"),
    "obstacle.regrowTimer": impl("combat.ts onObstacleDestroyed"),
    "obstacle.stonePlated": impl("combat.ts canDamageObstacle (needs a stonePiercing source)"),
    "obstacle.disableBuildingOccupied": impl("buildings.ts onBuildingObstacleDestroyed (occupiedDisabled)"),
    "obstacle.damageCeiling": impl("buildings.ts onBuildingObstacleDestroyed (ceilingDamaged)"),
    "obstacle.aabb": impl("entities.ts Obstacle bounds (broadphase and view culling)"),
    "obstacle.isTree": deferred("M8", "the tree climbing perk walks through trunks"),
    "obstacle.isWindow": impl("melee.ts swing rays ignore windows"),
    "obstacle.door": impl("doors.ts"),
    "obstacle.material": data("merged into the def by the original wall and door factories"),
    "obstacle.hinge": data("the door position is its hinge; the collision already includes the offset"),
    "obstacle.extents": data("wall half extents; the collision already includes them"),
    "obstacle.isWall": impl("buildings.ts breakWallAttachments and wall count"),
    "obstacle.teamId": impl("entities.ts Obstacle.teamId; faction side (placement.ts teamIdOf, survev genOnGrass)"),
    // doors
    "obstacle.door.interactionRad": impl("interact.ts interactableObstacles, doors.ts autoOpenDoors"),
    "obstacle.door.canUse": impl("doors.ts interactDoor"),
    "obstacle.door.openSpeed": client("panel animation speed"),
    "obstacle.door.openOneWay": impl("doors.ts toggleDoor / autoOpenDoors"),
    "obstacle.door.openDelay": impl("doors.ts interactDoor"),
    "obstacle.door.openOnce": impl("doors.ts interactDoor"),
    "obstacle.door.autoOpen": impl("doors.ts autoOpenDoors"),
    "obstacle.door.autoClose": impl("doors.ts toggleDoor / updateDoorTimers"),
    "obstacle.door.autoCloseDelay": impl("doors.ts toggleDoor / postponeAutoClose"),
    "obstacle.door.slideToOpen": impl("doors.ts toggleDoor"),
    "obstacle.door.slideOffset": impl("doors.ts toggleDoor"),
    "obstacle.door.spriteAnchor": client(),
    "obstacle.door.sound": client("open / close / change (door seq) / error sounds"),
    "obstacle.door.casingImg": client(),
    "obstacle.door.locked": impl("doors.ts interactDoor / autoOpenDoors / unlockDoor"),
    // buttons
    "obstacle.button.interactionRad": impl("interact.ts interactableObstacles"),
    "obstacle.button.interactionText": client(),
    "obstacle.button.useOnce": impl("interact.ts useButton / interactObstacle"),
    "obstacle.button.useType": impl("interact.ts useButton"),
    "obstacle.button.useDelay": impl("interact.ts useButton"),
    "obstacle.button.useDir": impl("interact.ts useButton -> doors.ts toggleDoor"),
    "obstacle.button.useImg": client(),
    "obstacle.button.offImg": client(),
    "obstacle.button.sound": impl("sound.on names a recorder's recording (RecorderEvent); otherwise client"),
    "obstacle.button.destroyOnUse": impl("interact.ts useButton / updateObstacleTimers"),
    "obstacle.button.useParticle": client(),
    // survev-only buttons (survev content wave stage 3): the Reserve's and the Cloud bunker's control panels, the
    // Augmenting Vat
    "obstacle.button.useStyle": impl("interact.ts useButton -> doors.ts scheduleDoor (close / open / toggle)"),
    "obstacle.button.useLock": impl("interact.ts useButton -> doors.ts (lock / unlock the doors)"),
    "obstacle.button.useCooldown": impl("interact.ts interactObstacle (interactCooldown)"),
    "obstacle.button.useExpiration": impl("interact.ts useButton -> doors.ts updateDoorTimers (memorized state)"),
    "obstacle.button.resetAfterCooldown": impl("interact.ts updateObstacleTimers (flips back after the cooldown)"),
    "obstacle.button.roleToPromote": impl("interact.ts useButton -> roles promote (Augmenting Vat: classless)"),
    "obstacle.button.isVat": client("survev client: vat interaction text and art"),
    // buildings
    "building.type": data(),
    "building.scale": data("buildings always spawn at scale 1"),
    "building.zIdx": impl("world.ts isOnWater surface priority"),
    "building.map": client("minimap"),
    "building.terrain": mapgen(),
    "building.teamId": mapgen("faction side (placement.ts teamIdOf; survev map.ts genOnGrass)"),
    "building.floor": impl("world.ts isOnWater, loot.ts floors"),
    "building.ceiling": impl("player.ts updateZoom, buildings.ts"),
    "building.mapObjects": mapgen(),
    "building.mapObstacleBounds": mapgen(),
    "building.puzzle": impl("puzzles.ts"),
    "building.ori": mapgen(),
    "building.oris": mapgen(),
    "building.mapGroundPatches": mapgen(),
    "building.bridgeLandBounds": mapgen(),
    "building.bridgeWaterBounds": mapgen(),
    "building.occupiedEmitters": client("run while occupied, stop for good with occupiedDisabled"),
    "building.goreRegion": impl("buildings.ts goreRegionKill (pool decal goreKills)"),
    "building.soundEmitters": client(),
    "building.healRegions": impl("surroundings.ts / buildings.ts healRegionRate"),
    "building.floor_images": factoryParam,
    "building.ceiling_images": factoryParam,
    "building.ceilingImg": factoryParam,
    "building.specialLoot": factoryParam,
    "building.topLeftObs": factoryParam,
    "building.topRightObs": factoryParam,
    "building.botRightObs": factoryParam,
    "building.ignoreMapSpawnReplacement": factoryParam,
    "building.decoration_01": factoryParam,
    "building.decoration_02": factoryParam,
    "building.groundTintLt": factoryParam,
    "building.groundTintDk": factoryParam,
    "building.tree_08c": factoryParam,
    "building.statue": factoryParam,
    "building.crate": factoryParam,
    "building.obs": factoryParam,
    "building.basement": factoryParam,
    "building.bonus_door": factoryParam,
    "building.porch_01": factoryParam,
    "building.bonus_room": factoryParam,
    "building.vault": factoryParam,
    "building.gold_box": factoryParam,
    "building.floor_loot": factoryParam,
    "building.stand": factoryParam,
    "building.cabin_mount": factoryParam,
    "building.entry_loot": factoryParam,
    "building.mid_obs_01": factoryParam,
    "building.center_loot": factoryParam,
    "building.left_loot": factoryParam,
    "building.right_loot": factoryParam,
    "building.grass_color": factoryParam,
    "building.tree_small": factoryParam,
    "building.tree_large": factoryParam,
    "building.ceiling.zoomRegions": impl("player.ts updateZoom (indoors, zoom, occupied)"),
    "building.ceiling.imgs": client(),
    "building.ceiling.vision": client("roof fade"),
    "building.ceiling.destroy": impl("entities.ts Building.wallsToDestroy, buildings.ts"),
    "building.ceiling.collision": unused("no logic reads it in survev's server or client"),
    "building.ceiling.damage": unused("obstacleCount: no logic reads it in survev's server or client"),
    "building.ceiling.destroy.wallCount": impl("buildings.ts onBuildingObstacleDestroyed (ceilingDead)"),
    "building.ceiling.destroy.particle": client("collapse effect"),
    "building.ceiling.destroy.particleCount": client("collapse effect"),
    "building.ceiling.destroy.residue": client("collapse residue sprite"),
    "building.ceiling.destroy.sound": client("collapse sound"),
    "building.floor.surfaces": impl("world.ts isOnWater, loot.ts"),
    "building.floor.imgs": client(),
    "building.puzzle.name": impl("puzzles.ts puzzleCode"),
    "building.puzzle.completeUseType": impl("puzzles.ts completePuzzle"),
    "building.puzzle.completeOffDelay": impl("puzzles.ts puzzlePieceToggled"),
    "building.puzzle.completeUseDelay": impl("puzzles.ts puzzlePieceToggled / updatePuzzle"),
    "building.puzzle.errorResetDelay": impl("puzzles.ts"),
    "building.puzzle.pieceResetDelay": impl("puzzles.ts"),
    "building.puzzle.sound": client("fail (errSeq) / complete (solved) sounds"),
    "building.mapObjects.type": mapgen(),
    "building.mapObjects.pos": mapgen(),
    "building.mapObjects.scale": mapgen(),
    "building.mapObjects.ori": mapgen(),
    "building.mapObjects.inheritOri": mapgen(),
    "building.mapObjects.ignoreMapSpawnReplacement": mapgen(),
    "building.mapObjects.layer": impl("generator.ts genBuilding (child.layer ?? building layer)"),
    "building.mapObjects.puzzlePiece": impl("generator.ts -> entities.ts Obstacle.puzzlePiece -> puzzles.ts"),
    "building.healRegions.collision": impl("entities.ts Building.healRegions"),
    "building.healRegions.healRate": impl("buildings.ts healRegionRate"),
    // structures
    "structure.type": data(),
    "structure.teamId": mapgen("faction side (placement.ts teamIdOf; survev map.ts genOnGrass)"),
    "structure.terrain": mapgen(),
    "structure.ori": mapgen(),
    "structure.mapObstacleBounds": mapgen(),
    "structure.layers": impl("generator.ts floors on layers 0 and 1"),
    "structure.stairs": impl("layers.ts checkStairs"),
    "structure.mask": client("cut out of the ground layer above the stairwell"),
    "structure.bunkerType": data("no logic reads it"),
    "structure.structureType": data("no logic reads it"),
    "structure.interiorSound": impl("puzzles.ts (interiorSoundAlt); the sound itself is client"),
    "structure.bridgeLandBounds": mapgen(),
    "structure.bridgeWaterBounds": mapgen(),
    "structure.stairs.collision": impl("layers.ts checkStairs"),
    "structure.stairs.downDir": impl("entities.ts Structure stairs halves, layers.ts aimLayerOf"),
    "structure.stairs.lootOnly": impl("layers.ts checkStairs, loot.ts belowBridge"),
    "structure.stairs.noCeilingReveal": client("ceilings stay closed near such stairs"),
    "structure.layers.type": mapgen(),
    "structure.layers.pos": mapgen(),
    "structure.layers.ori": mapgen(),
    "structure.layers.underground": client("underground backdrop (bridges are not underground)"),
    "structure.interiorSound.puzzle": impl("puzzles.ts puzzlePieceToggled"),
    "structure.interiorSound.sound": client(),
    "structure.interiorSound.soundAlt": client(),
    "structure.interiorSound.filter": client(),
    "structure.interiorSound.transitionTime": client(),
    "structure.interiorSound.soundAltPlayTime": client(),
    "structure.interiorSound.outsideMaxDist": client(),
    "structure.interiorSound.outsideVolume": client(),
    "structure.interiorSound.undergroundVolume": client(),
};
